# FROM nginx:alpine
# COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY ./dist /usr/share/nginx/html
# EXPOSE 80

# Use the official Nginx image
FROM nginx:alpine
 
# Copy the Nginx configuration file
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
 
# Copy the SSL certificate and key
COPY ./localhost.crt /etc/nginx/certs/localhost.crt
COPY ./localhost.key /etc/nginx/certs/localhost.key
 
# Copy the built frontend files
COPY ./dist /usr/share/nginx/html
 
# Expose port 443 for HTTPS
EXPOSE 443